---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-deployment-pyspark
  namespace: mdt
spec:
  annotations:
    project_name: seldon tf
    deployment_version: '0.10'
  name: pyspark-deployment
  oauth_key: oauth-key
  oauth_secret: oauth-secret
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: naughtytao/pyspark-model-wrapper:0.11
          imagePullPolicy: IfNotPresent
          name: pyspark-classifier
          resources:
            requests:
              memory: 32Mi
        terminationGracePeriodSeconds: 20
    graph:
      children: []
      name: pyspark-classifier
      endpoint:
        type: REST
      type: MODEL
    name: pyspark-predictor
    replicas: 1
    annotations:
      predictor_version: '0.10'
